spring:
  jpa:
    hibernate:
        ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${PGSQL_HOST:localhost}:${PGSQL_PORT:5432}/expenses_db
    username: ${PGSQL_USER:expenses}
    password: ${PGSQL_PWD:9AG7FghH}
    hikari:
      idle-timeout: 10000
  flyway:
    locations: classpath:db/migration
app:
  uploadPath: ${APP_UPLOAD_PATH:uploads}