version: '3'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    networks:
      - app-tier
    env_file:
      - postgres.env
    ports:
    - 5432:5432
networks:
  app-tier:
    driver: bridge